/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '../../src/index';
class CustomFormsModuleInjector extends import0.ɵNgModuleInjector<import1.CustomFormsModule> {
  _CustomFormsModule_0:import1.CustomFormsModule;
  constructor(parent:import0.Injector) {
    super(parent,([] as any[]),([] as any[]));
  }
  createInternal():import1.CustomFormsModule {
    this._CustomFormsModule_0 = new import1.CustomFormsModule();
    return this._CustomFormsModule_0;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import1.CustomFormsModule)) { return this._CustomFormsModule_0; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const CustomFormsModuleNgFactory:import0.NgModuleFactory<import1.CustomFormsModule> = new import0.NgModuleFactory<any>(CustomFormsModuleInjector,import1.CustomFormsModule);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvZGV2L1Byb2plY3RzL25nMi12YWxpZGF0aW9uL3NyYy9pbmRleC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9ob21lL2Rldi9Qcm9qZWN0cy9uZzItdmFsaWRhdGlvbi9zcmMvaW5kZXgudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
